[global]
username = "username"
use_keyring = true

device_name = "Thinkpad"
device_type = "computer"

# The audio bitrate. 96, 160 or 320 kbit/s
bitrate = 320

cache_path = "~/.cache/spotifyd"
no_audio_cache = false

