wallpaper {
    monitor = eDP-1
    path = /usr/share/backgrounds/archlinux/simple.png
    fit_mode = cover 
}
wallpaper {
    monitor = HDMI-A-1
    path = /usr/share/backgrounds/archlinux/simple.png
    fit_mode = cover 
}
